/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RadioshowsRouteImport } from './routes/radioshows/route'
import { Route as FavoritesRouteImport } from './routes/favorites/route'
import { Route as RadioshowIdRouteImport } from './routes/$radioshowId/route'

// Create/Update Routes

const RadioshowsRouteRoute = RadioshowsRouteImport.update({
  path: '/radioshows',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/radioshows/route.lazy').then((d) => d.Route),
)

const FavoritesRouteRoute = FavoritesRouteImport.update({
  path: '/favorites',
  getParentRoute: () => rootRoute,
} as any)

const RadioshowIdRouteRoute = RadioshowIdRouteImport.update({
  path: '/$radioshowId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/$radioshowId/route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$radioshowId': {
      preLoaderRoute: typeof RadioshowIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/favorites': {
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRoute
    }
    '/radioshows': {
      preLoaderRoute: typeof RadioshowsRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  RadioshowIdRouteRoute,
  FavoritesRouteRoute,
  RadioshowsRouteRoute,
])

/* prettier-ignore-end */
