/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RadioshowsRouteImport } from './routes/radioshows/route'
import { Route as RadioshowsRadioshowIdRouteImport } from './routes/radioshows/$radioshowId/route'

// Create/Update Routes

const RadioshowsRouteRoute = RadioshowsRouteImport.update({
  path: '/radioshows',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/radioshows/route.lazy').then((d) => d.Route),
)

const RadioshowsRadioshowIdRouteRoute = RadioshowsRadioshowIdRouteImport.update(
  {
    path: '/$radioshowId',
    getParentRoute: () => RadioshowsRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/radioshows/$radioshowId/route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/radioshows': {
      preLoaderRoute: typeof RadioshowsRouteImport
      parentRoute: typeof rootRoute
    }
    '/radioshows/$radioshowId': {
      preLoaderRoute: typeof RadioshowsRadioshowIdRouteImport
      parentRoute: typeof RadioshowsRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  RadioshowsRouteRoute.addChildren([RadioshowsRadioshowIdRouteRoute]),
])

/* prettier-ignore-end */
